
theme = "hugo_theme_pickles"
baseurl = "https://joecmarshall.com/"
languageCode = "en-us"
Title = "Joe M."
# Copyright notice. This is displayer in the footer.
copyright = "&copy; 2019 Joe Marshall"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "joecharmar"
  #facebook = "Your Facebook username"
  #instagram = "Your Instagram username"
  #googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  github = "marshaljoe"
  #gitlab = "Your GitLab username"
  #npm = "Your npm username"
  #codepen = "Your CodePen username"
  #dribbble = "Your Dribbble username"
  #fivehundredpx = "Your 500px username" # 500px
  #flickr = "Your Flickr username"
  #pinterest = "Your Pinterest username"
  #tumblr = "Your Tumblr username"
  #vimeo = "Your Vimeo username"
  #youtube = "Your YouTube username"
  linkedin = "joecmarshall"
  # Disqus shortname
  disqus = ""
  # Google Analytics API key.
  ga_api_key = "UA-105604576-1"
  author = "Joe Marshall"
  authorwebsite = "joecmarshall.com"
  # avatar = "/path/to/avatar"
  # contact = "mailto:joe@joecmarshall.com"
  bio = "Joe is a web application developer, independent security researcher, and writer. His first book, Hands-On Bug Hunting for Penetration Testers, is out now."
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Developer and Author from Austin, TX."
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/favicon.ico"

[[menu.main]]
    name = "Hands-On Bug Hunting"
    url = "https://handsonbughunting.com"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
